# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(979, 448)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_push_button = QtWidgets.QPushButton(self.widget)
        self.add_push_button.setObjectName("add_push_button")
        self.horizontalLayout.addWidget(self.add_push_button)
        self.start_push_button = QtWidgets.QPushButton(self.widget)
        self.start_push_button.setObjectName("start_push_button")
        self.horizontalLayout.addWidget(self.start_push_button)
        self.pause_push_button = QtWidgets.QPushButton(self.widget)
        self.pause_push_button.setObjectName("pause_push_button")
        self.horizontalLayout.addWidget(self.pause_push_button)
        self.remove_push_button = QtWidgets.QPushButton(self.widget)
        self.remove_push_button.setObjectName("remove_push_button")
        self.horizontalLayout.addWidget(self.remove_push_button)
        self.verticalLayout.addWidget(self.widget)
        self.table_view = QtWidgets.QTableView(self.centralwidget)
        self.table_view.setObjectName("table_view")
        self.verticalLayout.addWidget(self.table_view)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 979, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.add_push_button.setText(_translate("MainWindow", "Add"))
        self.start_push_button.setText(_translate("MainWindow", "Start Download"))
        self.pause_push_button.setText(_translate("MainWindow", "Pause Download"))
        self.remove_push_button.setText(_translate("MainWindow", "Remove"))
